# Generated by Django 3.2.6 on 2021-09-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200, null=True)),
                ('rta1', models.CharField(max_length=200, null=True)),
                ('rta2', models.CharField(max_length=200, null=True)),
                ('rta3', models.CharField(max_length=200, null=True)),
                ('correct', models.CharField(choices=[('rta1', 'Respuesta 1'), ('rta2', 'Respuesta 2'), ('rta3', 'Respuesta 3')], default=' ', max_length=4)),
            ],
            options={
                'db_table': 'cuestionario',
            },
        ),
    ]
